
DROP DATABASE IF EXISTS JUGADOR_BD;
CREATE DATABASE JUGADOR_BD;

USE JUGADOR_BD;

CREATE TABLE Jugadores(
	
	ID INTEGER PRIMARY KEY NOT NULL,
	NOMBRE TEXT NOT NULL,
	CONTRASEÑA TEXT NOT NULL

)ENGINE = InnoDB;

CREATE TABLE PARTIDAS(

	ID INTEGER PRIMARY KEY NOT NULL,
	FECHA TEXT NOT NULL
)ENGINE = InnoDB;

CREATE TABLE RELACION(

	IDJ INTEGER NOT NULL,
	IDP INTEGER NOT NULL,
	PUNTOS INTEGER NOT NULL,
	FOREIGN KEY (IDJ) REFERENCES Jugadores(ID),
	FOREIGN KEY (IDP) REFERENCES PARTIDAS(ID)
)ENGINE = InnoDB;

INSERT INTO Jugadores VALUES(1,'Juan','Albaricoque');
INSERT INTO Jugadores VALUES(2,'Pepe','Elvergalarga');
INSERT INTO Jugadores VALUES(3,'Maria','123abc');

INSERT INTO PARTIDAS VALUES(1, '12-03-2022');
INSERT INTO PARTIDAS VALUES(2, '13-03-2022');
INSERT INTO PARTIDAS VALUES(3, '14-03-2022');

INSERT INTO RELACION VALUES(1,1,60);
INSERT INTO RELACION VALUES(2,1,60);
INSERT INTO RELACION VALUES(3,2,60);

	
